import{a as y,i as h,S as p}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const g="https://pixabay.com/api/",L="44820639-952f0c833853b1e1c1ece8d2c",l=async(r,t=1)=>{try{return(await y.get(g,{params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(a){throw console.error("Error fetching images:",a),a}},d=r=>{const t=document.querySelector(".gallery");if(t.innerHTML="",r.length===0){h.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=r.map(s=>`
    <a href="${s.largeImageURL}" class="gallery-item">
      <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${s.likes}</p>
        <p class="info-item"><b>Views:</b> ${s.views}</p>
        <p class="info-item"><b>Comments:</b> ${s.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${s.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",a),new p(".gallery a").refresh()},u=()=>{document.querySelector(".loader").classList.remove("hidden")},m=()=>{document.querySelector(".loader").classList.add("hidden")},w=()=>{document.querySelector(".load-more").classList.remove("hidden")},f=()=>{document.querySelector(".load-more").classList.add("hidden")};let n=1,i="";const b=document.querySelector(".search-form"),S=document.querySelector(".search-input"),q=document.querySelector(".load-more");b.addEventListener("submit",async r=>{if(r.preventDefault(),i=S.value.trim(),!i){iziToast.warning({title:"Warning",message:"Please enter a search query!"});return}n=1,f(),u();try{const t=await l(i,n);d(t.hits),t.totalHits>15&&w()}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{m()}});q.addEventListener("click",async()=>{n+=1,u();try{const r=await l(i,n);d(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n*15>=r.totalHits&&(f(),iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
