import{a as L,i as a,S as b}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",P="44820639-952f0c833853b1e1c1ece8d2c",f=async(t,r=1,s=15)=>{try{return(await L.get(w,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}},y=(t,r=!1)=>{const s=document.querySelector(".gallery");if(r||(s.innerHTML=""),t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=t.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",n),new b(".gallery a").refresh()},h=()=>{document.querySelector(".loader").classList.remove("hidden")},g=()=>{document.querySelector(".loader").classList.add("hidden")},S=()=>{const t=document.querySelector(".load-more");t.classList.remove("hidden"),t.style.display="flex",t.style.justifyContent="center",t.style.marginTop="20px"},u=()=>{const t=document.querySelector(".load-more");t.classList.add("hidden"),t.style.display="none"};let i=1,l="",m=0;const c=15,v=document.querySelector(".search-form"),q=document.querySelector(".search-input"),E=document.querySelector(".load-more"),p=(t,r=15)=>Math.ceil(t/r);v.addEventListener("submit",async t=>{if(t.preventDefault(),l=q.value.trim(),!l){a.warning({title:"Warning",message:"Please enter a search query!"});return}i=1,u(),h();try{const r=await f(l,i,c);m=r.totalHits,y(r.hits),p(m,c)>i&&r.hits.length===c?S():(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});E.addEventListener("click",async()=>{i+=1,h();try{const t=await f(l,i,c);y(t.hits,!0);const r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"});const s=p(m,c);(i>=s||t.hits.length<c)&&(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
