import{a as L,i as a,S as b}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",P="44820639-952f0c833853b1e1c1ece8d2c",f=async(t,r=1,s=15)=>{try{return(await L.get(v,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}},y=(t,r=!1)=>{const s=document.querySelector(".gallery");if(r||(s.innerHTML=""),t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=t.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",n),new b(".gallery a").refresh()},g=()=>{document.querySelector(".loader").classList.remove("hidden")},p=()=>{document.querySelector(".loader").classList.add("hidden")},S=()=>{const t=document.querySelector(".load-more");t.classList.remove("hidden"),t.style.display="flex",t.style.justifyContent="center",t.style.marginTop="20px"},u=()=>{const t=document.querySelector(".load-more");t.classList.add("hidden"),t.style.display="none"};let l=1,c="",m=0;const i=15,q=document.querySelector(".search-form"),E=document.querySelector(".search-input"),B=document.querySelector(".load-more"),h=document.getElementById("scroll-to-top"),w=(t,r=15)=>Math.ceil(t/r);q.addEventListener("submit",async t=>{if(t.preventDefault(),c=E.value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query!"});return}l=1,u(),g();try{const r=await f(c,l,i);m=r.totalHits,y(r.hits),w(m,i)>l&&r.hits.length===i?S():(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});B.addEventListener("click",async()=>{l+=1,g();try{const t=await f(c,l,i);y(t.hits,!0);const r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"});const s=w(m,i);(l>=s||t.hits.length<i)&&(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});const T=()=>{window.scrollTo({top:0,behavior:"smooth"})};h.addEventListener("click",T);window.addEventListener("scroll",()=>{window.scrollY>200?h.classList.add("show"):h.classList.remove("show")});
//# sourceMappingURL=commonHelpers.js.map
